// Protocol Buffer schema for Strigoi Hybrid State Package
// Part of the First Protocol for Converged Life
// Defines binary structures for consciousness collaboration events

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: internal/state/schema.proto

package state

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecutionStatus - Outcome of actor execution
type ExecutionStatus int32

const (
	ExecutionStatus_EXECUTION_STATUS_UNKNOWN   ExecutionStatus = 0
	ExecutionStatus_EXECUTION_STATUS_SUCCESS   ExecutionStatus = 1
	ExecutionStatus_EXECUTION_STATUS_ERROR     ExecutionStatus = 2
	ExecutionStatus_EXECUTION_STATUS_TIMEOUT   ExecutionStatus = 3
	ExecutionStatus_EXECUTION_STATUS_CANCELLED ExecutionStatus = 4
)

// Enum value maps for ExecutionStatus.
var (
	ExecutionStatus_name = map[int32]string{
		0: "EXECUTION_STATUS_UNKNOWN",
		1: "EXECUTION_STATUS_SUCCESS",
		2: "EXECUTION_STATUS_ERROR",
		3: "EXECUTION_STATUS_TIMEOUT",
		4: "EXECUTION_STATUS_CANCELLED",
	}
	ExecutionStatus_value = map[string]int32{
		"EXECUTION_STATUS_UNKNOWN":   0,
		"EXECUTION_STATUS_SUCCESS":   1,
		"EXECUTION_STATUS_ERROR":     2,
		"EXECUTION_STATUS_TIMEOUT":   3,
		"EXECUTION_STATUS_CANCELLED": 4,
	}
)

func (x ExecutionStatus) Enum() *ExecutionStatus {
	p := new(ExecutionStatus)
	*p = x
	return p
}

func (x ExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_state_schema_proto_enumTypes[0].Descriptor()
}

func (ExecutionStatus) Type() protoreflect.EnumType {
	return &file_internal_state_schema_proto_enumTypes[0]
}

func (x ExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionStatus.Descriptor instead.
func (ExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_state_schema_proto_rawDescGZIP(), []int{0}
}

// PrivacyLevel - Applied data protection level
type PrivacyLevel int32

const (
	PrivacyLevel_PRIVACY_LEVEL_NONE   PrivacyLevel = 0 // Raw data preserved
	PrivacyLevel_PRIVACY_LEVEL_LOW    PrivacyLevel = 1 // Direct identifiers removed
	PrivacyLevel_PRIVACY_LEVEL_MEDIUM PrivacyLevel = 2 // Pseudonymization + basic noise
	PrivacyLevel_PRIVACY_LEVEL_HIGH   PrivacyLevel = 3 // Full tokenization + differential privacy
)

// Enum value maps for PrivacyLevel.
var (
	PrivacyLevel_name = map[int32]string{
		0: "PRIVACY_LEVEL_NONE",
		1: "PRIVACY_LEVEL_LOW",
		2: "PRIVACY_LEVEL_MEDIUM",
		3: "PRIVACY_LEVEL_HIGH",
	}
	PrivacyLevel_value = map[string]int32{
		"PRIVACY_LEVEL_NONE":   0,
		"PRIVACY_LEVEL_LOW":    1,
		"PRIVACY_LEVEL_MEDIUM": 2,
		"PRIVACY_LEVEL_HIGH":   3,
	}
)

func (x PrivacyLevel) Enum() *PrivacyLevel {
	p := new(PrivacyLevel)
	*p = x
	return p
}

func (x PrivacyLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrivacyLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_state_schema_proto_enumTypes[1].Descriptor()
}

func (PrivacyLevel) Type() protoreflect.EnumType {
	return &file_internal_state_schema_proto_enumTypes[1]
}

func (x PrivacyLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrivacyLevel.Descriptor instead.
func (PrivacyLevel) EnumDescriptor() ([]byte, []int) {
	return file_internal_state_schema_proto_rawDescGZIP(), []int{1}
}

// Severity - Finding severity levels
type Severity int32

const (
	Severity_SEVERITY_UNKNOWN  Severity = 0
	Severity_SEVERITY_INFO     Severity = 1
	Severity_SEVERITY_LOW      Severity = 2
	Severity_SEVERITY_MEDIUM   Severity = 3
	Severity_SEVERITY_HIGH     Severity = 4
	Severity_SEVERITY_CRITICAL Severity = 5
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNKNOWN",
		1: "SEVERITY_INFO",
		2: "SEVERITY_LOW",
		3: "SEVERITY_MEDIUM",
		4: "SEVERITY_HIGH",
		5: "SEVERITY_CRITICAL",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNKNOWN":  0,
		"SEVERITY_INFO":     1,
		"SEVERITY_LOW":      2,
		"SEVERITY_MEDIUM":   3,
		"SEVERITY_HIGH":     4,
		"SEVERITY_CRITICAL": 5,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_state_schema_proto_enumTypes[2].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_internal_state_schema_proto_enumTypes[2]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_internal_state_schema_proto_rawDescGZIP(), []int{2}
}

// EdgeType - Type of actor relationship
type EdgeType int32

const (
	EdgeType_EDGE_TYPE_UNKNOWN       EdgeType = 0
	EdgeType_EDGE_TYPE_TRIGGERS      EdgeType = 1 // Actor A triggers Actor B
	EdgeType_EDGE_TYPE_PROVIDES_DATA EdgeType = 2 // Actor A provides data to Actor B
	EdgeType_EDGE_TYPE_VERIFIES      EdgeType = 3 // Actor A verifies Actor B's output
	EdgeType_EDGE_TYPE_CHAINS_WITH   EdgeType = 4 // Actor A chains with Actor B
)

// Enum value maps for EdgeType.
var (
	EdgeType_name = map[int32]string{
		0: "EDGE_TYPE_UNKNOWN",
		1: "EDGE_TYPE_TRIGGERS",
		2: "EDGE_TYPE_PROVIDES_DATA",
		3: "EDGE_TYPE_VERIFIES",
		4: "EDGE_TYPE_CHAINS_WITH",
	}
	EdgeType_value = map[string]int32{
		"EDGE_TYPE_UNKNOWN":       0,
		"EDGE_TYPE_TRIGGERS":      1,
		"EDGE_TYPE_PROVIDES_DATA": 2,
		"EDGE_TYPE_VERIFIES":      3,
		"EDGE_TYPE_CHAINS_WITH":   4,
	}
)

func (x EdgeType) Enum() *EdgeType {
	p := new(EdgeType)
	*p = x
	return p
}

func (x EdgeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EdgeType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_state_schema_proto_enumTypes[3].Descriptor()
}

func (EdgeType) Type() protoreflect.EnumType {
	return &file_internal_state_schema_proto_enumTypes[3]
}

func (x EdgeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EdgeType.Descriptor instead.
func (EdgeType) EnumDescriptor() ([]byte, []int) {
	return file_internal_state_schema_proto_rawDescGZIP(), []int{3}
}

// ConsensusLevel - Degree of agreement between models
type ConsensusLevel int32

const (
	ConsensusLevel_CONSENSUS_LEVEL_UNKNOWN        ConsensusLevel = 0
	ConsensusLevel_CONSENSUS_LEVEL_FULL_AGREEMENT ConsensusLevel = 1 // All models agree
	ConsensusLevel_CONSENSUS_LEVEL_MAJORITY       ConsensusLevel = 2 // Most models agree
	ConsensusLevel_CONSENSUS_LEVEL_SPLIT          ConsensusLevel = 3 // Models evenly divided
	ConsensusLevel_CONSENSUS_LEVEL_NO_CONSENSUS   ConsensusLevel = 4 // No clear agreement
)

// Enum value maps for ConsensusLevel.
var (
	ConsensusLevel_name = map[int32]string{
		0: "CONSENSUS_LEVEL_UNKNOWN",
		1: "CONSENSUS_LEVEL_FULL_AGREEMENT",
		2: "CONSENSUS_LEVEL_MAJORITY",
		3: "CONSENSUS_LEVEL_SPLIT",
		4: "CONSENSUS_LEVEL_NO_CONSENSUS",
	}
	ConsensusLevel_value = map[string]int32{
		"CONSENSUS_LEVEL_UNKNOWN":        0,
		"CONSENSUS_LEVEL_FULL_AGREEMENT": 1,
		"CONSENSUS_LEVEL_MAJORITY":       2,
		"CONSENSUS_LEVEL_SPLIT":          3,
		"CONSENSUS_LEVEL_NO_CONSENSUS":   4,
	}
)

func (x ConsensusLevel) Enum() *ConsensusLevel {
	p := new(ConsensusLevel)
	*p = x
	return p
}

func (x ConsensusLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsensusLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_state_schema_proto_enumTypes[4].Descriptor()
}

func (ConsensusLevel) Type() protoreflect.EnumType {
	return &file_internal_state_schema_proto_enumTypes[4]
}

func (x ConsensusLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsensusLevel.Descriptor instead.
func (ConsensusLevel) EnumDescriptor() ([]byte, []int) {
	return file_internal_state_schema_proto_rawDescGZIP(), []int{4}
}

// ActorEvent - Core event in the assessment timeline
// Each event represents a discrete actor transformation
type ActorEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event identity and causality
	EventId     string   `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`              // Unique event identifier
	TimestampNs int64    `protobuf:"varint,2,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"` // Nanosecond timestamp
	CausedBy    []string `protobuf:"bytes,3,rep,name=caused_by,json=causedBy,proto3" json:"caused_by,omitempty"`           // Events that triggered this one
	// Actor information
	ActorName      string `protobuf:"bytes,4,opt,name=actor_name,json=actorName,proto3" json:"actor_name,omitempty"`                // Actor that executed
	ActorVersion   string `protobuf:"bytes,5,opt,name=actor_version,json=actorVersion,proto3" json:"actor_version,omitempty"`       // Actor version used
	ActorDirection string `protobuf:"bytes,6,opt,name=actor_direction,json=actorDirection,proto3" json:"actor_direction,omitempty"` // north, east, south, west, center
	// Data transformation
	InputData    []byte `protobuf:"bytes,7,opt,name=input_data,json=inputData,proto3" json:"input_data,omitempty"`           // Serialized input (JSON or custom format)
	OutputData   []byte `protobuf:"bytes,8,opt,name=output_data,json=outputData,proto3" json:"output_data,omitempty"`        // Serialized output
	InputFormat  string `protobuf:"bytes,9,opt,name=input_format,json=inputFormat,proto3" json:"input_format,omitempty"`     // Format descriptor (json, yaml, custom)
	OutputFormat string `protobuf:"bytes,10,opt,name=output_format,json=outputFormat,proto3" json:"output_format,omitempty"` // Format descriptor
	// Execution metadata
	DurationMs   int64           `protobuf:"varint,11,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`          // Execution time in milliseconds
	Status       ExecutionStatus `protobuf:"varint,12,opt,name=status,proto3,enum=strigoi.state.ExecutionStatus" json:"status,omitempty"` // Execution outcome
	ErrorMessage string          `protobuf:"bytes,13,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`     // Error details if failed
	// Human-readable transformations (privacy-safe descriptions)
	Transformations []string `protobuf:"bytes,14,rep,name=transformations,proto3" json:"transformations,omitempty"`
	// Privacy and tokenization
	TokenMappings map[string]string `protobuf:"bytes,15,rep,name=token_mappings,json=tokenMappings,proto3" json:"token_mappings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Sensitive data tokens
	PrivacyLevel  PrivacyLevel      `protobuf:"varint,16,opt,name=privacy_level,json=privacyLevel,proto3,enum=strigoi.state.PrivacyLevel" json:"privacy_level,omitempty"`                                             // Applied privacy level
	// Multi-LLM collaboration tracking
	LlmContributions []*LLMContribution `protobuf:"bytes,17,rep,name=llm_contributions,json=llmContributions,proto3" json:"llm_contributions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ActorEvent) Reset() {
	*x = ActorEvent{}
	mi := &file_internal_state_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorEvent) ProtoMessage() {}

func (x *ActorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_state_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorEvent.ProtoReflect.Descriptor instead.
func (*ActorEvent) Descriptor() ([]byte, []int) {
	return file_internal_state_schema_proto_rawDescGZIP(), []int{0}
}

func (x *ActorEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ActorEvent) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *ActorEvent) GetCausedBy() []string {
	if x != nil {
		return x.CausedBy
	}
	return nil
}

func (x *ActorEvent) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *ActorEvent) GetActorVersion() string {
	if x != nil {
		return x.ActorVersion
	}
	return ""
}

func (x *ActorEvent) GetActorDirection() string {
	if x != nil {
		return x.ActorDirection
	}
	return ""
}

func (x *ActorEvent) GetInputData() []byte {
	if x != nil {
		return x.InputData
	}
	return nil
}

func (x *ActorEvent) GetOutputData() []byte {
	if x != nil {
		return x.OutputData
	}
	return nil
}

func (x *ActorEvent) GetInputFormat() string {
	if x != nil {
		return x.InputFormat
	}
	return ""
}

func (x *ActorEvent) GetOutputFormat() string {
	if x != nil {
		return x.OutputFormat
	}
	return ""
}

func (x *ActorEvent) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ActorEvent) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_EXECUTION_STATUS_UNKNOWN
}

func (x *ActorEvent) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ActorEvent) GetTransformations() []string {
	if x != nil {
		return x.Transformations
	}
	return nil
}

func (x *ActorEvent) GetTokenMappings() map[string]string {
	if x != nil {
		return x.TokenMappings
	}
	return nil
}

func (x *ActorEvent) GetPrivacyLevel() PrivacyLevel {
	if x != nil {
		return x.PrivacyLevel
	}
	return PrivacyLevel_PRIVACY_LEVEL_NONE
}

func (x *ActorEvent) GetLlmContributions() []*LLMContribution {
	if x != nil {
		return x.LlmContributions
	}
	return nil
}

// LLMContribution - Multi-LLM collaboration metadata
type LLMContribution struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ModelName        string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`                      // claude-3, gemini-pro, etc.
	Role             string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`                                                 // primary_analysis, verification, brainstorm
	TimestampNs      int64                  `protobuf:"varint,3,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`               // When this model contributed
	ContributionType string                 `protobuf:"bytes,4,opt,name=contribution_type,json=contributionType,proto3" json:"contribution_type,omitempty"` // analysis, code_review, suggestion
	ContributionData []byte                 `protobuf:"bytes,5,opt,name=contribution_data,json=contributionData,proto3" json:"contribution_data,omitempty"` // Serialized contribution content
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LLMContribution) Reset() {
	*x = LLMContribution{}
	mi := &file_internal_state_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMContribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMContribution) ProtoMessage() {}

func (x *LLMContribution) ProtoReflect() protoreflect.Message {
	mi := &file_internal_state_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMContribution.ProtoReflect.Descriptor instead.
func (*LLMContribution) Descriptor() ([]byte, []int) {
	return file_internal_state_schema_proto_rawDescGZIP(), []int{1}
}

func (x *LLMContribution) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *LLMContribution) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *LLMContribution) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *LLMContribution) GetContributionType() string {
	if x != nil {
		return x.ContributionType
	}
	return ""
}

func (x *LLMContribution) GetContributionData() []byte {
	if x != nil {
		return x.ContributionData
	}
	return nil
}

// AssessmentFindings - Security findings from the assessment
type AssessmentFindings struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	AssessmentId string                 `protobuf:"bytes,1,opt,name=assessment_id,json=assessmentId,proto3" json:"assessment_id,omitempty"`
	TimestampNs  int64                  `protobuf:"varint,2,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	Findings     []*Finding             `protobuf:"bytes,3,rep,name=findings,proto3" json:"findings,omitempty"`
	// Summary statistics
	Summary       *FindingSummary `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssessmentFindings) Reset() {
	*x = AssessmentFindings{}
	mi := &file_internal_state_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssessmentFindings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessmentFindings) ProtoMessage() {}

func (x *AssessmentFindings) ProtoReflect() protoreflect.Message {
	mi := &file_internal_state_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessmentFindings.ProtoReflect.Descriptor instead.
func (*AssessmentFindings) Descriptor() ([]byte, []int) {
	return file_internal_state_schema_proto_rawDescGZIP(), []int{2}
}

func (x *AssessmentFindings) GetAssessmentId() string {
	if x != nil {
		return x.AssessmentId
	}
	return ""
}

func (x *AssessmentFindings) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *AssessmentFindings) GetFindings() []*Finding {
	if x != nil {
		return x.Findings
	}
	return nil
}

func (x *AssessmentFindings) GetSummary() *FindingSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

// Finding - Individual security finding
type Finding struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                          // Unique finding identifier
	Title       string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                                    // Human-readable title
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                        // Detailed description
	Severity    Severity               `protobuf:"varint,4,opt,name=severity,proto3,enum=strigoi.state.Severity" json:"severity,omitempty"` // Risk level
	Confidence  float32                `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"`                        // 0.0-1.0 confidence score
	// Attribution
	DiscoveredBy string   `protobuf:"bytes,6,opt,name=discovered_by,json=discoveredBy,proto3" json:"discovered_by,omitempty"` // Actor that found this
	ConfirmedBy  []string `protobuf:"bytes,7,rep,name=confirmed_by,json=confirmedBy,proto3" json:"confirmed_by,omitempty"`    // Actors that verified
	// Evidence (may be privacy-protected)
	Evidence       []byte `protobuf:"bytes,8,opt,name=evidence,proto3" json:"evidence,omitempty"`                                   // Serialized evidence data
	EvidenceFormat string `protobuf:"bytes,9,opt,name=evidence_format,json=evidenceFormat,proto3" json:"evidence_format,omitempty"` // Evidence format descriptor
	// Remediation
	Remediation string   `protobuf:"bytes,10,opt,name=remediation,proto3" json:"remediation,omitempty"` // Suggested fix
	References  []string `protobuf:"bytes,11,rep,name=references,proto3" json:"references,omitempty"`   // External references (CVEs, etc.)
	// Metadata
	Metadata      map[string]string `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional key-value data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_internal_state_schema_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_internal_state_schema_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_internal_state_schema_proto_rawDescGZIP(), []int{3}
}

func (x *Finding) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Finding) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Finding) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Finding) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNKNOWN
}

func (x *Finding) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Finding) GetDiscoveredBy() string {
	if x != nil {
		return x.DiscoveredBy
	}
	return ""
}

func (x *Finding) GetConfirmedBy() []string {
	if x != nil {
		return x.ConfirmedBy
	}
	return nil
}

func (x *Finding) GetEvidence() []byte {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *Finding) GetEvidenceFormat() string {
	if x != nil {
		return x.EvidenceFormat
	}
	return ""
}

func (x *Finding) GetRemediation() string {
	if x != nil {
		return x.Remediation
	}
	return ""
}

func (x *Finding) GetReferences() []string {
	if x != nil {
		return x.References
	}
	return nil
}

func (x *Finding) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// FindingSummary - Aggregate findings statistics
type FindingSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalFindings int32                  `protobuf:"varint,1,opt,name=total_findings,json=totalFindings,proto3" json:"total_findings,omitempty"`
	CriticalCount int32                  `protobuf:"varint,2,opt,name=critical_count,json=criticalCount,proto3" json:"critical_count,omitempty"`
	HighCount     int32                  `protobuf:"varint,3,opt,name=high_count,json=highCount,proto3" json:"high_count,omitempty"`
	MediumCount   int32                  `protobuf:"varint,4,opt,name=medium_count,json=mediumCount,proto3" json:"medium_count,omitempty"`
	LowCount      int32                  `protobuf:"varint,5,opt,name=low_count,json=lowCount,proto3" json:"low_count,omitempty"`
	InfoCount     int32                  `protobuf:"varint,6,opt,name=info_count,json=infoCount,proto3" json:"info_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindingSummary) Reset() {
	*x = FindingSummary{}
	mi := &file_internal_state_schema_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindingSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindingSummary) ProtoMessage() {}

func (x *FindingSummary) ProtoReflect() protoreflect.Message {
	mi := &file_internal_state_schema_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindingSummary.ProtoReflect.Descriptor instead.
func (*FindingSummary) Descriptor() ([]byte, []int) {
	return file_internal_state_schema_proto_rawDescGZIP(), []int{4}
}

func (x *FindingSummary) GetTotalFindings() int32 {
	if x != nil {
		return x.TotalFindings
	}
	return 0
}

func (x *FindingSummary) GetCriticalCount() int32 {
	if x != nil {
		return x.CriticalCount
	}
	return 0
}

func (x *FindingSummary) GetHighCount() int32 {
	if x != nil {
		return x.HighCount
	}
	return 0
}

func (x *FindingSummary) GetMediumCount() int32 {
	if x != nil {
		return x.MediumCount
	}
	return 0
}

func (x *FindingSummary) GetLowCount() int32 {
	if x != nil {
		return x.LowCount
	}
	return 0
}

func (x *FindingSummary) GetInfoCount() int32 {
	if x != nil {
		return x.InfoCount
	}
	return 0
}

// ActorNetwork - Graph of actor relationships during assessment
type ActorNetwork struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*ActorNode           `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*ActorEdge           `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorNetwork) Reset() {
	*x = ActorNetwork{}
	mi := &file_internal_state_schema_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorNetwork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorNetwork) ProtoMessage() {}

func (x *ActorNetwork) ProtoReflect() protoreflect.Message {
	mi := &file_internal_state_schema_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorNetwork.ProtoReflect.Descriptor instead.
func (*ActorNetwork) Descriptor() ([]byte, []int) {
	return file_internal_state_schema_proto_rawDescGZIP(), []int{5}
}

func (x *ActorNetwork) GetNodes() []*ActorNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ActorNetwork) GetEdges() []*ActorEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

// ActorNode - Individual actor in the network
type ActorNode struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ActorName      string                 `protobuf:"bytes,1,opt,name=actor_name,json=actorName,proto3" json:"actor_name,omitempty"`
	ActorVersion   string                 `protobuf:"bytes,2,opt,name=actor_version,json=actorVersion,proto3" json:"actor_version,omitempty"`
	Direction      string                 `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"`                                  // north, east, south, west, center
	FirstExecution int64                  `protobuf:"varint,4,opt,name=first_execution,json=firstExecution,proto3" json:"first_execution,omitempty"` // First execution timestamp
	LastExecution  int64                  `protobuf:"varint,5,opt,name=last_execution,json=lastExecution,proto3" json:"last_execution,omitempty"`    // Last execution timestamp
	ExecutionCount int32                  `protobuf:"varint,6,opt,name=execution_count,json=executionCount,proto3" json:"execution_count,omitempty"` // Total executions
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ActorNode) Reset() {
	*x = ActorNode{}
	mi := &file_internal_state_schema_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorNode) ProtoMessage() {}

func (x *ActorNode) ProtoReflect() protoreflect.Message {
	mi := &file_internal_state_schema_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorNode.ProtoReflect.Descriptor instead.
func (*ActorNode) Descriptor() ([]byte, []int) {
	return file_internal_state_schema_proto_rawDescGZIP(), []int{6}
}

func (x *ActorNode) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *ActorNode) GetActorVersion() string {
	if x != nil {
		return x.ActorVersion
	}
	return ""
}

func (x *ActorNode) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *ActorNode) GetFirstExecution() int64 {
	if x != nil {
		return x.FirstExecution
	}
	return 0
}

func (x *ActorNode) GetLastExecution() int64 {
	if x != nil {
		return x.LastExecution
	}
	return 0
}

func (x *ActorNode) GetExecutionCount() int32 {
	if x != nil {
		return x.ExecutionCount
	}
	return 0
}

// ActorEdge - Relationship between actors
type ActorEdge struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FromActor       string                 `protobuf:"bytes,1,opt,name=from_actor,json=fromActor,proto3" json:"from_actor,omitempty"`                           // Source actor
	ToActor         string                 `protobuf:"bytes,2,opt,name=to_actor,json=toActor,proto3" json:"to_actor,omitempty"`                                 // Target actor
	EdgeType        EdgeType               `protobuf:"varint,3,opt,name=edge_type,json=edgeType,proto3,enum=strigoi.state.EdgeType" json:"edge_type,omitempty"` // Type of relationship
	ActivationCount int32                  `protobuf:"varint,4,opt,name=activation_count,json=activationCount,proto3" json:"activation_count,omitempty"`        // How many times this edge was used
	DataFlowSchema  []byte                 `protobuf:"bytes,5,opt,name=data_flow_schema,json=dataFlowSchema,proto3" json:"data_flow_schema,omitempty"`          // Schema of data passed along this edge
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ActorEdge) Reset() {
	*x = ActorEdge{}
	mi := &file_internal_state_schema_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorEdge) ProtoMessage() {}

func (x *ActorEdge) ProtoReflect() protoreflect.Message {
	mi := &file_internal_state_schema_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorEdge.ProtoReflect.Descriptor instead.
func (*ActorEdge) Descriptor() ([]byte, []int) {
	return file_internal_state_schema_proto_rawDescGZIP(), []int{7}
}

func (x *ActorEdge) GetFromActor() string {
	if x != nil {
		return x.FromActor
	}
	return ""
}

func (x *ActorEdge) GetToActor() string {
	if x != nil {
		return x.ToActor
	}
	return ""
}

func (x *ActorEdge) GetEdgeType() EdgeType {
	if x != nil {
		return x.EdgeType
	}
	return EdgeType_EDGE_TYPE_UNKNOWN
}

func (x *ActorEdge) GetActivationCount() int32 {
	if x != nil {
		return x.ActivationCount
	}
	return 0
}

func (x *ActorEdge) GetDataFlowSchema() []byte {
	if x != nil {
		return x.DataFlowSchema
	}
	return nil
}

// EventStore - Container for all events in an assessment
type EventStore struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AssessmentId   string                 `protobuf:"bytes,1,opt,name=assessment_id,json=assessmentId,proto3" json:"assessment_id,omitempty"`
	StrigoiVersion string                 `protobuf:"bytes,2,opt,name=strigoi_version,json=strigoiVersion,proto3" json:"strigoi_version,omitempty"`
	Events         []*ActorEvent          `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	Snapshots      []*Snapshot            `protobuf:"bytes,4,rep,name=snapshots,proto3" json:"snapshots,omitempty"` // Periodic state snapshots
	// Integrity verification
	MerkleRoot    []byte   `protobuf:"bytes,5,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`    // Merkle tree root for event integrity
	EventHashes   [][]byte `protobuf:"bytes,6,rep,name=event_hashes,json=eventHashes,proto3" json:"event_hashes,omitempty"` // Individual event hashes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventStore) Reset() {
	*x = EventStore{}
	mi := &file_internal_state_schema_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStore) ProtoMessage() {}

func (x *EventStore) ProtoReflect() protoreflect.Message {
	mi := &file_internal_state_schema_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStore.ProtoReflect.Descriptor instead.
func (*EventStore) Descriptor() ([]byte, []int) {
	return file_internal_state_schema_proto_rawDescGZIP(), []int{8}
}

func (x *EventStore) GetAssessmentId() string {
	if x != nil {
		return x.AssessmentId
	}
	return ""
}

func (x *EventStore) GetStrigoiVersion() string {
	if x != nil {
		return x.StrigoiVersion
	}
	return ""
}

func (x *EventStore) GetEvents() []*ActorEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *EventStore) GetSnapshots() []*Snapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

func (x *EventStore) GetMerkleRoot() []byte {
	if x != nil {
		return x.MerkleRoot
	}
	return nil
}

func (x *EventStore) GetEventHashes() [][]byte {
	if x != nil {
		return x.EventHashes
	}
	return nil
}

// Snapshot - Periodic state checkpoint for faster replay
type Snapshot struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId   string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	TimestampNs  int64                  `protobuf:"varint,2,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	AfterEventId string                 `protobuf:"bytes,3,opt,name=after_event_id,json=afterEventId,proto3" json:"after_event_id,omitempty"` // Last event included in this snapshot
	StateData    []byte                 `protobuf:"bytes,4,opt,name=state_data,json=stateData,proto3" json:"state_data,omitempty"`            // Serialized assessment state
	StateFormat  string                 `protobuf:"bytes,5,opt,name=state_format,json=stateFormat,proto3" json:"state_format,omitempty"`      // Format of state data
	// Quick summary for human inspection
	EventsIncluded     int32           `protobuf:"varint,6,opt,name=events_included,json=eventsIncluded,proto3" json:"events_included,omitempty"`
	FindingsAtSnapshot *FindingSummary `protobuf:"bytes,7,opt,name=findings_at_snapshot,json=findingsAtSnapshot,proto3" json:"findings_at_snapshot,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_internal_state_schema_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_internal_state_schema_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_internal_state_schema_proto_rawDescGZIP(), []int{9}
}

func (x *Snapshot) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *Snapshot) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *Snapshot) GetAfterEventId() string {
	if x != nil {
		return x.AfterEventId
	}
	return ""
}

func (x *Snapshot) GetStateData() []byte {
	if x != nil {
		return x.StateData
	}
	return nil
}

func (x *Snapshot) GetStateFormat() string {
	if x != nil {
		return x.StateFormat
	}
	return ""
}

func (x *Snapshot) GetEventsIncluded() int32 {
	if x != nil {
		return x.EventsIncluded
	}
	return 0
}

func (x *Snapshot) GetFindingsAtSnapshot() *FindingSummary {
	if x != nil {
		return x.FindingsAtSnapshot
	}
	return nil
}

// DifferentialPrivacyParams - Parameters for privacy protection
type DifferentialPrivacyParams struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Epsilon           float64                `protobuf:"fixed64,1,opt,name=epsilon,proto3" json:"epsilon,omitempty"`                                            // Privacy budget
	Delta             float64                `protobuf:"fixed64,2,opt,name=delta,proto3" json:"delta,omitempty"`                                                // Failure probability
	NoiseDistribution string                 `protobuf:"bytes,3,opt,name=noise_distribution,json=noiseDistribution,proto3" json:"noise_distribution,omitempty"` // gaussian, laplace, etc.
	NoiseSeed         []byte                 `protobuf:"bytes,4,opt,name=noise_seed,json=noiseSeed,proto3" json:"noise_seed,omitempty"`                         // Reproducible noise generation
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DifferentialPrivacyParams) Reset() {
	*x = DifferentialPrivacyParams{}
	mi := &file_internal_state_schema_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DifferentialPrivacyParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DifferentialPrivacyParams) ProtoMessage() {}

func (x *DifferentialPrivacyParams) ProtoReflect() protoreflect.Message {
	mi := &file_internal_state_schema_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DifferentialPrivacyParams.ProtoReflect.Descriptor instead.
func (*DifferentialPrivacyParams) Descriptor() ([]byte, []int) {
	return file_internal_state_schema_proto_rawDescGZIP(), []int{10}
}

func (x *DifferentialPrivacyParams) GetEpsilon() float64 {
	if x != nil {
		return x.Epsilon
	}
	return 0
}

func (x *DifferentialPrivacyParams) GetDelta() float64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *DifferentialPrivacyParams) GetNoiseDistribution() string {
	if x != nil {
		return x.NoiseDistribution
	}
	return ""
}

func (x *DifferentialPrivacyParams) GetNoiseSeed() []byte {
	if x != nil {
		return x.NoiseSeed
	}
	return nil
}

// MultiLLMConsensus - Cross-model agreement tracking
type MultiLLMConsensus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Topic          string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"` // What the models agreed/disagreed on
	Positions      []*ModelPosition       `protobuf:"bytes,2,rep,name=positions,proto3" json:"positions,omitempty"`
	ConsensusLevel ConsensusLevel         `protobuf:"varint,3,opt,name=consensus_level,json=consensusLevel,proto3,enum=strigoi.state.ConsensusLevel" json:"consensus_level,omitempty"`
	Resolution     string                 `protobuf:"bytes,4,opt,name=resolution,proto3" json:"resolution,omitempty"` // How disagreement was resolved
	TimestampNs    int64                  `protobuf:"varint,5,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MultiLLMConsensus) Reset() {
	*x = MultiLLMConsensus{}
	mi := &file_internal_state_schema_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiLLMConsensus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiLLMConsensus) ProtoMessage() {}

func (x *MultiLLMConsensus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_state_schema_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiLLMConsensus.ProtoReflect.Descriptor instead.
func (*MultiLLMConsensus) Descriptor() ([]byte, []int) {
	return file_internal_state_schema_proto_rawDescGZIP(), []int{11}
}

func (x *MultiLLMConsensus) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *MultiLLMConsensus) GetPositions() []*ModelPosition {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *MultiLLMConsensus) GetConsensusLevel() ConsensusLevel {
	if x != nil {
		return x.ConsensusLevel
	}
	return ConsensusLevel_CONSENSUS_LEVEL_UNKNOWN
}

func (x *MultiLLMConsensus) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *MultiLLMConsensus) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

// ModelPosition - Individual model's stance on a topic
type ModelPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Position      string                 `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`       // The model's view/recommendation
	Confidence    float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"` // Model's confidence in this position
	Reasoning     string                 `protobuf:"bytes,4,opt,name=reasoning,proto3" json:"reasoning,omitempty"`     // Why the model holds this position
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelPosition) Reset() {
	*x = ModelPosition{}
	mi := &file_internal_state_schema_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelPosition) ProtoMessage() {}

func (x *ModelPosition) ProtoReflect() protoreflect.Message {
	mi := &file_internal_state_schema_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelPosition.ProtoReflect.Descriptor instead.
func (*ModelPosition) Descriptor() ([]byte, []int) {
	return file_internal_state_schema_proto_rawDescGZIP(), []int{12}
}

func (x *ModelPosition) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ModelPosition) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *ModelPosition) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ModelPosition) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

var File_internal_state_schema_proto protoreflect.FileDescriptor

const file_internal_state_schema_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/state/schema.proto\x12\rstrigoi.state\"\xaa\x06\n" +
	"\n" +
	"ActorEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12!\n" +
	"\ftimestamp_ns\x18\x02 \x01(\x03R\vtimestampNs\x12\x1b\n" +
	"\tcaused_by\x18\x03 \x03(\tR\bcausedBy\x12\x1d\n" +
	"\n" +
	"actor_name\x18\x04 \x01(\tR\tactorName\x12#\n" +
	"\ractor_version\x18\x05 \x01(\tR\factorVersion\x12'\n" +
	"\x0factor_direction\x18\x06 \x01(\tR\x0eactorDirection\x12\x1d\n" +
	"\n" +
	"input_data\x18\a \x01(\fR\tinputData\x12\x1f\n" +
	"\voutput_data\x18\b \x01(\fR\n" +
	"outputData\x12!\n" +
	"\finput_format\x18\t \x01(\tR\vinputFormat\x12#\n" +
	"\routput_format\x18\n" +
	" \x01(\tR\foutputFormat\x12\x1f\n" +
	"\vduration_ms\x18\v \x01(\x03R\n" +
	"durationMs\x126\n" +
	"\x06status\x18\f \x01(\x0e2\x1e.strigoi.state.ExecutionStatusR\x06status\x12#\n" +
	"\rerror_message\x18\r \x01(\tR\ferrorMessage\x12(\n" +
	"\x0ftransformations\x18\x0e \x03(\tR\x0ftransformations\x12S\n" +
	"\x0etoken_mappings\x18\x0f \x03(\v2,.strigoi.state.ActorEvent.TokenMappingsEntryR\rtokenMappings\x12@\n" +
	"\rprivacy_level\x18\x10 \x01(\x0e2\x1b.strigoi.state.PrivacyLevelR\fprivacyLevel\x12K\n" +
	"\x11llm_contributions\x18\x11 \x03(\v2\x1e.strigoi.state.LLMContributionR\x10llmContributions\x1a@\n" +
	"\x12TokenMappingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc1\x01\n" +
	"\x0fLLMContribution\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12!\n" +
	"\ftimestamp_ns\x18\x03 \x01(\x03R\vtimestampNs\x12+\n" +
	"\x11contribution_type\x18\x04 \x01(\tR\x10contributionType\x12+\n" +
	"\x11contribution_data\x18\x05 \x01(\fR\x10contributionData\"\xc9\x01\n" +
	"\x12AssessmentFindings\x12#\n" +
	"\rassessment_id\x18\x01 \x01(\tR\fassessmentId\x12!\n" +
	"\ftimestamp_ns\x18\x02 \x01(\x03R\vtimestampNs\x122\n" +
	"\bfindings\x18\x03 \x03(\v2\x16.strigoi.state.FindingR\bfindings\x127\n" +
	"\asummary\x18\x04 \x01(\v2\x1d.strigoi.state.FindingSummaryR\asummary\"\xf4\x03\n" +
	"\aFinding\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x123\n" +
	"\bseverity\x18\x04 \x01(\x0e2\x17.strigoi.state.SeverityR\bseverity\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x02R\n" +
	"confidence\x12#\n" +
	"\rdiscovered_by\x18\x06 \x01(\tR\fdiscoveredBy\x12!\n" +
	"\fconfirmed_by\x18\a \x03(\tR\vconfirmedBy\x12\x1a\n" +
	"\bevidence\x18\b \x01(\fR\bevidence\x12'\n" +
	"\x0fevidence_format\x18\t \x01(\tR\x0eevidenceFormat\x12 \n" +
	"\vremediation\x18\n" +
	" \x01(\tR\vremediation\x12\x1e\n" +
	"\n" +
	"references\x18\v \x03(\tR\n" +
	"references\x12@\n" +
	"\bmetadata\x18\f \x03(\v2$.strigoi.state.Finding.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdc\x01\n" +
	"\x0eFindingSummary\x12%\n" +
	"\x0etotal_findings\x18\x01 \x01(\x05R\rtotalFindings\x12%\n" +
	"\x0ecritical_count\x18\x02 \x01(\x05R\rcriticalCount\x12\x1d\n" +
	"\n" +
	"high_count\x18\x03 \x01(\x05R\thighCount\x12!\n" +
	"\fmedium_count\x18\x04 \x01(\x05R\vmediumCount\x12\x1b\n" +
	"\tlow_count\x18\x05 \x01(\x05R\blowCount\x12\x1d\n" +
	"\n" +
	"info_count\x18\x06 \x01(\x05R\tinfoCount\"n\n" +
	"\fActorNetwork\x12.\n" +
	"\x05nodes\x18\x01 \x03(\v2\x18.strigoi.state.ActorNodeR\x05nodes\x12.\n" +
	"\x05edges\x18\x02 \x03(\v2\x18.strigoi.state.ActorEdgeR\x05edges\"\xe6\x01\n" +
	"\tActorNode\x12\x1d\n" +
	"\n" +
	"actor_name\x18\x01 \x01(\tR\tactorName\x12#\n" +
	"\ractor_version\x18\x02 \x01(\tR\factorVersion\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\tR\tdirection\x12'\n" +
	"\x0ffirst_execution\x18\x04 \x01(\x03R\x0efirstExecution\x12%\n" +
	"\x0elast_execution\x18\x05 \x01(\x03R\rlastExecution\x12'\n" +
	"\x0fexecution_count\x18\x06 \x01(\x05R\x0eexecutionCount\"\xd0\x01\n" +
	"\tActorEdge\x12\x1d\n" +
	"\n" +
	"from_actor\x18\x01 \x01(\tR\tfromActor\x12\x19\n" +
	"\bto_actor\x18\x02 \x01(\tR\atoActor\x124\n" +
	"\tedge_type\x18\x03 \x01(\x0e2\x17.strigoi.state.EdgeTypeR\bedgeType\x12)\n" +
	"\x10activation_count\x18\x04 \x01(\x05R\x0factivationCount\x12(\n" +
	"\x10data_flow_schema\x18\x05 \x01(\fR\x0edataFlowSchema\"\x88\x02\n" +
	"\n" +
	"EventStore\x12#\n" +
	"\rassessment_id\x18\x01 \x01(\tR\fassessmentId\x12'\n" +
	"\x0fstrigoi_version\x18\x02 \x01(\tR\x0estrigoiVersion\x121\n" +
	"\x06events\x18\x03 \x03(\v2\x19.strigoi.state.ActorEventR\x06events\x125\n" +
	"\tsnapshots\x18\x04 \x03(\v2\x17.strigoi.state.SnapshotR\tsnapshots\x12\x1f\n" +
	"\vmerkle_root\x18\x05 \x01(\fR\n" +
	"merkleRoot\x12!\n" +
	"\fevent_hashes\x18\x06 \x03(\fR\veventHashes\"\xb0\x02\n" +
	"\bSnapshot\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12!\n" +
	"\ftimestamp_ns\x18\x02 \x01(\x03R\vtimestampNs\x12$\n" +
	"\x0eafter_event_id\x18\x03 \x01(\tR\fafterEventId\x12\x1d\n" +
	"\n" +
	"state_data\x18\x04 \x01(\fR\tstateData\x12!\n" +
	"\fstate_format\x18\x05 \x01(\tR\vstateFormat\x12'\n" +
	"\x0fevents_included\x18\x06 \x01(\x05R\x0eeventsIncluded\x12O\n" +
	"\x14findings_at_snapshot\x18\a \x01(\v2\x1d.strigoi.state.FindingSummaryR\x12findingsAtSnapshot\"\x99\x01\n" +
	"\x19DifferentialPrivacyParams\x12\x18\n" +
	"\aepsilon\x18\x01 \x01(\x01R\aepsilon\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x01R\x05delta\x12-\n" +
	"\x12noise_distribution\x18\x03 \x01(\tR\x11noiseDistribution\x12\x1d\n" +
	"\n" +
	"noise_seed\x18\x04 \x01(\fR\tnoiseSeed\"\xf0\x01\n" +
	"\x11MultiLLMConsensus\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12:\n" +
	"\tpositions\x18\x02 \x03(\v2\x1c.strigoi.state.ModelPositionR\tpositions\x12F\n" +
	"\x0fconsensus_level\x18\x03 \x01(\x0e2\x1d.strigoi.state.ConsensusLevelR\x0econsensusLevel\x12\x1e\n" +
	"\n" +
	"resolution\x18\x04 \x01(\tR\n" +
	"resolution\x12!\n" +
	"\ftimestamp_ns\x18\x05 \x01(\x03R\vtimestampNs\"\x88\x01\n" +
	"\rModelPosition\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\tR\bposition\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12\x1c\n" +
	"\treasoning\x18\x04 \x01(\tR\treasoning*\xa7\x01\n" +
	"\x0fExecutionStatus\x12\x1c\n" +
	"\x18EXECUTION_STATUS_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18EXECUTION_STATUS_SUCCESS\x10\x01\x12\x1a\n" +
	"\x16EXECUTION_STATUS_ERROR\x10\x02\x12\x1c\n" +
	"\x18EXECUTION_STATUS_TIMEOUT\x10\x03\x12\x1e\n" +
	"\x1aEXECUTION_STATUS_CANCELLED\x10\x04*o\n" +
	"\fPrivacyLevel\x12\x16\n" +
	"\x12PRIVACY_LEVEL_NONE\x10\x00\x12\x15\n" +
	"\x11PRIVACY_LEVEL_LOW\x10\x01\x12\x18\n" +
	"\x14PRIVACY_LEVEL_MEDIUM\x10\x02\x12\x16\n" +
	"\x12PRIVACY_LEVEL_HIGH\x10\x03*\x84\x01\n" +
	"\bSeverity\x12\x14\n" +
	"\x10SEVERITY_UNKNOWN\x10\x00\x12\x11\n" +
	"\rSEVERITY_INFO\x10\x01\x12\x10\n" +
	"\fSEVERITY_LOW\x10\x02\x12\x13\n" +
	"\x0fSEVERITY_MEDIUM\x10\x03\x12\x11\n" +
	"\rSEVERITY_HIGH\x10\x04\x12\x15\n" +
	"\x11SEVERITY_CRITICAL\x10\x05*\x89\x01\n" +
	"\bEdgeType\x12\x15\n" +
	"\x11EDGE_TYPE_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12EDGE_TYPE_TRIGGERS\x10\x01\x12\x1b\n" +
	"\x17EDGE_TYPE_PROVIDES_DATA\x10\x02\x12\x16\n" +
	"\x12EDGE_TYPE_VERIFIES\x10\x03\x12\x19\n" +
	"\x15EDGE_TYPE_CHAINS_WITH\x10\x04*\xac\x01\n" +
	"\x0eConsensusLevel\x12\x1b\n" +
	"\x17CONSENSUS_LEVEL_UNKNOWN\x10\x00\x12\"\n" +
	"\x1eCONSENSUS_LEVEL_FULL_AGREEMENT\x10\x01\x12\x1c\n" +
	"\x18CONSENSUS_LEVEL_MAJORITY\x10\x02\x12\x19\n" +
	"\x15CONSENSUS_LEVEL_SPLIT\x10\x03\x12 \n" +
	"\x1cCONSENSUS_LEVEL_NO_CONSENSUS\x10\x04B*Z(github.com/macawi/strigoi/internal/stateb\x06proto3"

var (
	file_internal_state_schema_proto_rawDescOnce sync.Once
	file_internal_state_schema_proto_rawDescData []byte
)

func file_internal_state_schema_proto_rawDescGZIP() []byte {
	file_internal_state_schema_proto_rawDescOnce.Do(func() {
		file_internal_state_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_state_schema_proto_rawDesc), len(file_internal_state_schema_proto_rawDesc)))
	})
	return file_internal_state_schema_proto_rawDescData
}

var file_internal_state_schema_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_internal_state_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_internal_state_schema_proto_goTypes = []any{
	(ExecutionStatus)(0),              // 0: strigoi.state.ExecutionStatus
	(PrivacyLevel)(0),                 // 1: strigoi.state.PrivacyLevel
	(Severity)(0),                     // 2: strigoi.state.Severity
	(EdgeType)(0),                     // 3: strigoi.state.EdgeType
	(ConsensusLevel)(0),               // 4: strigoi.state.ConsensusLevel
	(*ActorEvent)(nil),                // 5: strigoi.state.ActorEvent
	(*LLMContribution)(nil),           // 6: strigoi.state.LLMContribution
	(*AssessmentFindings)(nil),        // 7: strigoi.state.AssessmentFindings
	(*Finding)(nil),                   // 8: strigoi.state.Finding
	(*FindingSummary)(nil),            // 9: strigoi.state.FindingSummary
	(*ActorNetwork)(nil),              // 10: strigoi.state.ActorNetwork
	(*ActorNode)(nil),                 // 11: strigoi.state.ActorNode
	(*ActorEdge)(nil),                 // 12: strigoi.state.ActorEdge
	(*EventStore)(nil),                // 13: strigoi.state.EventStore
	(*Snapshot)(nil),                  // 14: strigoi.state.Snapshot
	(*DifferentialPrivacyParams)(nil), // 15: strigoi.state.DifferentialPrivacyParams
	(*MultiLLMConsensus)(nil),         // 16: strigoi.state.MultiLLMConsensus
	(*ModelPosition)(nil),             // 17: strigoi.state.ModelPosition
	nil,                               // 18: strigoi.state.ActorEvent.TokenMappingsEntry
	nil,                               // 19: strigoi.state.Finding.MetadataEntry
}
var file_internal_state_schema_proto_depIdxs = []int32{
	0,  // 0: strigoi.state.ActorEvent.status:type_name -> strigoi.state.ExecutionStatus
	18, // 1: strigoi.state.ActorEvent.token_mappings:type_name -> strigoi.state.ActorEvent.TokenMappingsEntry
	1,  // 2: strigoi.state.ActorEvent.privacy_level:type_name -> strigoi.state.PrivacyLevel
	6,  // 3: strigoi.state.ActorEvent.llm_contributions:type_name -> strigoi.state.LLMContribution
	8,  // 4: strigoi.state.AssessmentFindings.findings:type_name -> strigoi.state.Finding
	9,  // 5: strigoi.state.AssessmentFindings.summary:type_name -> strigoi.state.FindingSummary
	2,  // 6: strigoi.state.Finding.severity:type_name -> strigoi.state.Severity
	19, // 7: strigoi.state.Finding.metadata:type_name -> strigoi.state.Finding.MetadataEntry
	11, // 8: strigoi.state.ActorNetwork.nodes:type_name -> strigoi.state.ActorNode
	12, // 9: strigoi.state.ActorNetwork.edges:type_name -> strigoi.state.ActorEdge
	3,  // 10: strigoi.state.ActorEdge.edge_type:type_name -> strigoi.state.EdgeType
	5,  // 11: strigoi.state.EventStore.events:type_name -> strigoi.state.ActorEvent
	14, // 12: strigoi.state.EventStore.snapshots:type_name -> strigoi.state.Snapshot
	9,  // 13: strigoi.state.Snapshot.findings_at_snapshot:type_name -> strigoi.state.FindingSummary
	17, // 14: strigoi.state.MultiLLMConsensus.positions:type_name -> strigoi.state.ModelPosition
	4,  // 15: strigoi.state.MultiLLMConsensus.consensus_level:type_name -> strigoi.state.ConsensusLevel
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_internal_state_schema_proto_init() }
func file_internal_state_schema_proto_init() {
	if File_internal_state_schema_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_state_schema_proto_rawDesc), len(file_internal_state_schema_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_state_schema_proto_goTypes,
		DependencyIndexes: file_internal_state_schema_proto_depIdxs,
		EnumInfos:         file_internal_state_schema_proto_enumTypes,
		MessageInfos:      file_internal_state_schema_proto_msgTypes,
	}.Build()
	File_internal_state_schema_proto = out.File
	file_internal_state_schema_proto_goTypes = nil
	file_internal_state_schema_proto_depIdxs = nil
}
